# Generated by Django 2.2.5 on 2019-10-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('Titulos', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, null=True)),
                ('Apellido', models.CharField(max_length=50, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('pais', models.CharField(default='', max_length=50)),
                ('lugar', models.CharField(default='', max_length=50)),
                ('Opinion', models.TextField(null=True)),
            ],
        ),
    ]
