# Generated by Django 2.2.5 on 2019-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turist',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
