# Generated by Django 2.2.5 on 2019-10-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turist',
            name='rut',
        ),
    ]
