# Generated by Django 2.2.5 on 2019-10-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('Titulo', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='turist',
            name='lugar',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='turist',
            name='pais',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='turist',
            name='rut',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='turist',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='turist',
            name='Apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turist',
            name='Nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turist',
            name='Opinion',
            field=models.TextField(null=True),
        ),
    ]
