# Generated by Django 2.2.5 on 2019-10-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0002_auto_20191011_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='Titulo',
            new_name='Titulos',
        ),
    ]
