# Generated by Django 2.2.5 on 2019-11-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0002_turist_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turist',
            name='date_of_birth',
        ),
    ]
